---
title: "Income Statement Compilation"
author: "Noe Navarro"
date: "October 16, 2018"
output: html_document
---


```{r}
library(rstudioapi)

library(ggplot2)
library(ggvis)
library(ggthemes)

library(purrr)
library(lazyeval)
library(RODBC) # Creates a connection to SQL Database
library(odbc)
library(sqldf) # Allows for the use of SQL language
library(reshape2) #Data Transformation
library(DT)
library(dygraphs)
library(xts)
library(lubridate)
library(reshape2)

library(plyr)
library(dplyr)
library(dbplyr)

library(R2HTML)
library(CenterIS)

library(supclust)

library(jsonlite)
library(RCurl)

library(tidyr)
library(data.table)
library(rlist)
library(testthat)


```


```{r}

# SQL Database ----
con.FinAccounting = DBI::dbConnect(odbc::odbc(), 
      Driver = "SQL Server",
      Server = "OPSREPORT02.UHAUL.AMERCO.ORG",
      Database = "FinAccounting",
      UID = rstudioapi::askForPassword("Database user"),
      PWD = rstudioapi::askForPassword("Database password"),
      Port = 1433)


# collect database ----
  sap_uhi_group <- dplyr::tbl(con.FinAccounting, "SAP_IS_UHAL_GROUP")
test_db <- collect(sap_uhi_group)

```



#** Lender Reporting Accounts (Rob)**

```{r}

# Import csv ----
accounts <-
  read.csv("\\\\adfs01.uhi.amerco\\departments\\mia\\group\\MIA\\Noe\\Projects\\Same Store & Cap Ex\\Report\\Quarterly Acquisitions\\income_statement_accounts.csv")


colnames(accounts)[1] <- "SAP_number"

```


#** SQL Table Import**

In the following code chunk, we will manually compile the income statement format using the SQL DB. 

```{r}

# Income Statement Compilation ----
storage_income <- 
  accounts %>%
  filter(Line.Item == 'STORAGE INCOME')

  sales <-
    accounts %>%
    filter(Line.Item == 'SALES')

    cogs <- 
      accounts %>%
      filter(Line.Item == 'COST OF SALES')

      misc_income <- 
        accounts %>%
        filter(Line.Item == 'MISCELLANEOUS INCOME')

        ubox_income <- 
          accounts %>%
          filter(grepl("U-BOX", accounts$Line.Item))
        
          ubox_income$Line.Item = 'U-BOX'
          
          
          umove_net_commission <-
            accounts %>%
            filter(Line.Item == 'U-MOVE NET COMMISSION')
          
            third_party_lease <-
              accounts %>%
              filter(Line.Item == 'THIRD PARTY LEASE')
            
              intercompany_lease <-
                accounts %>%
                filter(Line.Item == 'INTERCOMPANY LEASE')
            

            # Expenses ----
              personnel_exp <-
                accounts %>%
                filter(Line.Item == 'PERSONNEL')
              
                repairs_and_maintenance <- 
                  accounts %>%
                  filter(Line.Item == 'REPAIRS AND MAINTENANCE/GENERAL')
                
                  utility_exp <- 
                    accounts %>%
                    filter(Line.Item == 'UTILITIES')
                  
                    telephone_exp <- 
                      accounts %>% 
                      filter(Line.Item == 'TELEPHONE')
                    
                      advertising_exp <-
                        accounts %>%
                        filter(Line.Item == 'ADVERTISING')
                      
                        supplies <-
                          accounts %>%
                          filter(Line.Item == 'SUPPLIES')
                        
                        rent_eqp_land_bldg <- 
                          accounts %>%
                          filter(Line.Item == 'RENT-EQUIPMENT/LAND AND BLDGS')

                      liability_insurance <-
                        accounts %>%
                        filter(Line.Item == 'LIABILITY INSURANCE')
                      
                  property_tax_exp <-
                    accounts %>%
                    filter(Line.Item == 'PROPERTY TAX')
                  
              bad_debt_expense <- 
                accounts %>%
                filter(Line.Item == 'BAD DEBT EXPENSE')
              
          other_op_exp <- 
            accounts %>%
            filter(Line.Item == "OTHER OPERATING EXPENSE")
                        

# Accounts Data Frame ----
chart_of_accounts <-
  bind_rows(storage_income, 
            sales, 
            cogs,
            misc_income,
            ubox_income,
            umove_net_commission,
            third_party_lease,
            intercompany_lease,
            personnel_exp,
            repairs_and_maintenance, 
            utility_exp,
            telephone_exp,
            advertising_exp,
            supplies,
            rent_eqp_land_bldg,
            liability_insurance,
            property_tax_exp,
            bad_debt_expense,
            other_op_exp)
          
          
  # Character conversion ----
  chart_of_accounts$SAP_number <-
    as.character(chart_of_accounts$SAP_number)
          
  # Isolate SAP Account Numbers ----
  sap_accounts <-
    chart_of_accounts %>%
    select(SAP_number)
          
  
          
  # List of Line Item Descriptions ----
  line_items <-         
    chart_of_accounts %>%
      distinct(Line.Item)
          
    line_items <- line_items$Line.Item
    
    # List Creation ----      
    line_item_list <- lapply(line_items, as.list)
      
```



# *Data Check Function Update*

```{r}

data_check_center <-
  
  function(x){
    
  require("dplyr")
  require("lazyeval")
  require("purrr")
    
  #vector of list
  list.vector = list()
  list.complete = list()
  
  i = 1

  #Filter Criteria
  d = IS.Trend.Cash %>% filter(CURRENCY == 'Group' & SPLIT == 'ALL' & `PROFIT CENTER` == x & `NET OPERATING INCOME` != 0) %>% arrange(MONTH)

  #Create a local copy of the data frame
  b = collect(d)
    
  if(nrow(b) > 0){
    list.vector[[i]] = 1
  } else {
    list.complete[[i]] = x
  }
  return(list.complete)
}



```



```{r}

# Original Function ----
MonthofOperation.Start = function (x){

  #Library
  require("dplyr")
  require("lazyeval")
  require("purrr") #makes iteration problems easier to solve

  start_of_record = min(x$MONTH)
  return(start_of_record)
  
}

# --------------------------------------------------------------------------------------------------------------------------------------------------------

# New Function ----
month_opertation_start <- function(x) {
  
  require(dplyr)
  require(lazyeval)
  require(purrr)
  
  IS_trend <- income_statment_compilation(x, accounts = sap_accounts$SAP_number)

  min_month <- 
    IS_trend %>%
    filter(`Line Item` == 'NOI' & Value != 0)
  
    min_month <- 
      min(min_month$Date)
  
      return(min_month)

}



```



```{r Date Difference Function }

monnb <- function(d) { lt <- as.POSIXlt(as.Date(d, origin = "1900-01-01")); lt$year*12 + lt$mon } 
mondf <- function(d1, d2) { monnb(d2) - monnb(d1) }

```


```{r Individual Line Item Function }

  
line_item_function <- function(x){
     
    # x = list of line items 
     require(dplyr)
     require(purrr)
     
     # Date Range for missing line items ----
     min_is_month <- min(db$MONTH)
     max_is_month <- as.Date('2018-09-01')
     
     # Line Item IS compilation ----
     line_item_is <- 
       db %>%
       filter(`Line Item` == x[1]) %>%
       group_by(MONTH, `Line Item`) %>%
       summarize(Amount = sum(Amount))
     
     # Calculate date difference ----
     date_diff <- 
       mondf(min_is_month, min(line_item_is$MONTH))
     
     
    # Check for date_diff NA ----
    if(is.na(date_diff) == TRUE){  
     
    full_date <- 
       seq.Date(from = min_is_month, to = max_is_month, by = "month")
     
     full_fill <- 
       as.data.frame(full_date)
     
     # Rename to Month ----
     colnames(full_fill) <- "MONTH"
     
     full_fill$`Line Item` <- as.character(paste(x[1]))
     full_fill$Amount = 0
     
     line_item_is <- as.tbl(full_fill)
     
     # Filter for max date
     line_item_is <-
        line_item_is %>%
        filter(MONTH < '2018-10-01')
     
     
    } else if(date_diff > 0){
     
     
  # Date Difference Logical Flow. 
  # if Date > 0; min Month is lower than Line Item Minimum. We will need to fill in the remaining dates ---- 

     date_seq <-
     seq.Date(from = min_is_month, to = min(line_item_is$MONTH) - 1, by = "month")
   
     fill_df <-
     as.data.frame(date_seq)
   
    # Rename column ----
     colnames(fill_df) <- "MONTH"
     
     fill_df$`Line Item` <- paste(x[1])
     fill_df$Amount = 0
   
    # Bind Dataframes ----
     line_item_is <-
       bind_rows(fill_df, line_item_is)
     
     # tbl conversion ----
     line_item_is <- as.tbl(line_item_is)
     
      # Filter for max date ----
      line_item_is <-
        line_item_is %>%
        filter(MONTH < '2018-10-01')
     
    } else if(date_diff == 0){
    
      line_item_is <- as.tbl(line_item_is)
      
      # Filter for max date ----
      line_item_is <-
        line_item_is %>%
        filter(MONTH < '2018-10-01')
      
    }
  
     return(line_item_is)
}



```





```{r}

income_statment_compilation <- function(x, accounts){
  
  # x = list of profit centers 
  # accounts = sap accounts to be used 
  
  require(dplyr)
  require(lazyeval)
  require(purrr)
  require(reshape2)
  
  # ------------------------------------------------
  # Step 1: Filter for Profit Center & Account List 
  # ------------------------------------------------
  
  # Filter SQL Database  & Collect ----
  db <-
  sap_uhi_group %>% 
    filter(`PROFIT CENTER` %in% x & 
             ACCOUNT %in% accounts &
             `Fiscal Year` >= 2015)
  
    db <- collect(db)
  
# Reformat database ----
colnames(db)[11] <- 4
colnames(db)[12] <- 5
colnames(db)[13] <- 6
colnames(db)[14] <- 7
colnames(db)[15] <- 8
colnames(db)[16] <- 9
colnames(db)[17] <- 10
colnames(db)[18] <- 11
colnames(db)[19] <- 12
colnames(db)[20] <- 1
colnames(db)[21] <- 2
colnames(db)[22] <- 3
  

  # Eliminate Unecessary columns ----
  db <-
    db[ , -c(1,3,4,5,9,10,23,24,26,27)]

    db <- 
      melt(db, id = c('PROFIT CENTER', "MEntity", "ACCOUNT", "DESCRIPTION", "Fiscal Year"))
    
# Rename columns ----
colnames(db)[3] <-  "SAP_number"   
colnames(db)[7] <- "Amount"
colnames(db)[6] <- "Cal_Month"

  db$Cal_Month <- as.character(db$Cal_Month)
  db$Cal_Month <- as.numeric(db$Cal_Month)
  db$SAP_number <- as.character(db$SAP_number)

# Creation of Calendar "MONTH" column ----
db$Cal_Year = " "

for (i in 1:length(db$`PROFIT CENTER`)){
  
  if(db$Cal_Month[i] >= 4 & db$Cal_Month[i] <= 12){
    
    db$Cal_Year[i] = db$`Fiscal Year`[i] - 1
    
  } else {
    
    db$Cal_Year[i] = db$`Fiscal Year`[i] 
    
  }
  
}

  
 db$MONTH <- 
   paste(db$Cal_Year, db$Cal_Month, 1, sep = "-")
  
   db$MONTH <- as.Date(db$MONTH, format = "%Y-%m-%d") 

    
  # Compilation of income statement ----
  db <-
    left_join(db, chart_of_accounts[ ,c(1,4)], by = "SAP_number")
   
    colnames(db)[10] <- "Line Item"
    
    
#------------------------------------------
# Step 2: Individual Line Item Compilation
# -----------------------------------------
  
  # This step will ensure all Line Items and Months are represented within the income statement for NOI calculation. If they are not, dedault value = 0
  aggregate_df <- 
    lapply(line_item_list, line_item_function)  
    
      
  return(aggregate_df)

}


```


```{r Test New Income Statement Function }


map(quarter_list, income_statment_compilation, accounts = sap_accounts$SAP_number)


```





```{r}

# Step by Step TEst of Line Item Function ----
line_item_function <- function(x){
     
    # x = list of line items 
     require(dplyr)
     require(purrr)
     
     # Date Range for missing line items ----
     min_is_month <- min(db$MONTH)
     max_is_month <- as.Date('2018-09-01')
     
     # Line Item IS compilation ----
     line_item_is <- 
       db %>%
       filter(`Line Item` == x[1]) %>%
       group_by(MONTH, `Line Item`) %>%
       summarize(Amount = sum(Amount))
     
     # Calculate date difference ----
     date_diff <- 
       mondf(min_is_month, min(line_item_is$MONTH))
     
     
    # Check for date_diff NA ----
    if(is.na(date_diff) == TRUE){  
     
    full_date <- 
       seq.Date(from = min_is_month, to = max_is_month, by = "month")
     
     full_fill <- 
       as.data.frame(full_date)
     
     # Rename to Month ----
     colnames(full_fill) <- "MONTH"
     
     full_fill$`Line Item` <- as.character(paste(x[1]))
     full_fill$Amount = 0
     
     line_item_is <- as.tbl(full_fill)
     
     # Filter for max date
     line_item_is <-
        line_item_is %>%
        filter(MONTH < '2018-10-01')
     
     
    } else if(date_diff > 0){
     
     
  # Date Difference Logical Flow. 
  # if Date > 0; min Month is lower than Line Item Minimum. We will need to fill in the remaining dates ---- 

     date_seq <-
     seq.Date(from = min_is_month, to = min(line_item_is$MONTH) - 1, by = "month")
   
     fill_df <-
     as.data.frame(date_seq)
   
    # Rename column ----
     colnames(fill_df) <- "MONTH"
     
     fill_df$`Line Item` <- paste(x[1])
     fill_df$Amount = 0
   
    # Bind Dataframes ----
     line_item_is <-
       bind_rows(fill_df, line_item_is)
     
     # tbl conversion ----
     line_item_is <- as.tbl(line_item_is)
     
      # Filter for max date ----
      line_item_is <-
        line_item_is %>%
        filter(MONTH < '2018-10-01')
     
    } else if(date_diff == 0){
    
      line_item_is <- as.tbl(line_item_is)
      
      # Filter for max date ----
      line_item_is <-
        line_item_is %>%
        filter(MONTH < '2018-10-01')
      
    }
  
     
     return(line_item_is)
     
}

# ------------------------------------
# Test Collapse of Data Frame ----

test_function <- 
  lapply(line_item_list, line_item_function)

  # Collapse List of Data Frames into 1 ----
  aggregate_df <-
    ldply(test_function, as.data.frame)
    
  # Need to flip signs of certain accounts ----
  # Apply this to multiple profit centers ----




```




```{r Original Income Statement Function }



income_statment_compilation <- function(x, accounts){
  
  # x = list of profit centers 
  # accounts = sap accounts to be used 
  
  require(dplyr)
  require(lazyeval)
  require(purrr)
  require(reshape2)
  
  # ------------------------------------------------
  # Step 1: Filter for Profit Center & Account List 
  # ------------------------------------------------
  
  # Filter SQL Database  & Collect ----
  db <-
  sap_uhi_group %>% 
    filter(`PROFIT CENTER` %in% x & 
             ACCOUNT %in% accounts &
             `Fiscal Year` >= 2015)
  
    db <- collect(db)
  
# Reformat database ----
colnames(db)[11] <- 4
colnames(db)[12] <- 5
colnames(db)[13] <- 6
colnames(db)[14] <- 7
colnames(db)[15] <- 8
colnames(db)[16] <- 9
colnames(db)[17] <- 10
colnames(db)[18] <- 11
colnames(db)[19] <- 12
colnames(db)[20] <- 1
colnames(db)[21] <- 2
colnames(db)[22] <- 3
  

  # Eliminate Unecessary columns ----
  db <-
    db[ , -c(1,3,4,5,9,10,23,24,26,27)]

    db <- 
      melt(db, id = c('PROFIT CENTER', "MEntity", "ACCOUNT", "DESCRIPTION", "Fiscal Year"))
    
# Rename columns ----
colnames(db)[3] <-  "SAP_number"   
colnames(db)[7] <- "Amount"
colnames(db)[6] <- "Cal_Month"

  db$Cal_Month <- as.character(db$Cal_Month)
  db$Cal_Month <- as.numeric(db$Cal_Month)
  db$SAP_number <- as.character(db$SAP_number)

# Creation of Calendar "MONTH" column ----
db$Cal_Year = " "

for (i in 1:length(db$`PROFIT CENTER`)){
  
  if(db$Cal_Month[i] >= 4 & db$Cal_Month[i] <= 12){
    
    db$Cal_Year[i] = db$`Fiscal Year`[i] - 1
    
  } else {
    
    db$Cal_Year[i] = db$`Fiscal Year`[i] 
    
  }
  
}

  
 db$MONTH <- 
   paste(db$Cal_Year, db$Cal_Month, 1, sep = "-")
  
   db$MONTH <- as.Date(db$MONTH, format = "%Y-%m-%d") 

    
  # Compilation of income statement ----
  db <-
    left_join(db, chart_of_accounts[ ,c(1,4)], by = "SAP_number")
   
    colnames(db)[10] <- "Line Item"
    
    
  #------------------------------------------
  # Step 2: Individual Line Item Compilation
  # -----------------------------------------
  
  # This step will ensure all Line Items and Months are represented within the income statement for NOI calculation. If they are not, dedault value = 0
    
  # Summarize Income Statement ----
  db <-
    db %>%
    group_by(MONTH, `Line Item`) %>%
    summarize(Value = sum(Amount))
    
  # Flip Sings coming through as negative ----  
  for (i in 1:length(db$Value)){
    
    if(db$`Line Item`[i] == 'MISCELLANEOUS INCOME') {
      
      db$Value[i] = -db$Value[i]
      
    } else if(db$`Line Item`[i] == 'SALES'){
      
      db$Value[i] = -db$Value[i]
      
    } else if(db$`Line Item`[i] == 'U-MOVE NET COMMISSION'){
      
      db$Value[i] = -db$Value[i]
      
    } else if(db$`Line Item`[i] == 'U-BOX OTHER INCOME'){
      
      db$Value[i] = -db$Value[i]
      
    } else if(db$`Line Item`[i] == 'U-BOX STORAGE INCOME'){
      
      db$Value[i] = -db$Value[i]
      
    } else if(db$`Line Item`[i] == 'U-BOX DELIVERY INCOME'){
      
      db$Value[i] = -db$Value[i]
      
    } else if(db$`Line Item`[i] == "STORAGE INCOME"){
      
      db$Value[i] = -db$Value[i]
      
    }
      
  }
    
    
    
# -------------------------
# Step 3: Horizontal Format
# -------------------------
    
 # Convert to horizontal format ----
 db <- 
     tidyr::spread(db, `Line Item`, Value)
 
   # Replace NA with 0 ----
   db[is.na(db)] <- 0    
 
 # Calculate NOI ----   

# if(!grepl("U-BOX", colnames(db))){
   
# db <- 
# db %>%
#   mutate(NOI = `STORAGE INCOME` + SALES + `MISCELLANEOUS INCOME` + `U-MOVE NET COMMISSION` - `COST OF SALES` - ADVERTISING - `LIABILITY INSURANCE` - PERSONNEL - `RENT-EQUIPMENT/LAND AND BLDGS` - `REPAIRS AND MAINTENANCE/GENERAL` - SUPPLIES - TELEPHONE - UTILITIES - `OTHER OPERATING EXPENSE`)
   
 
# } else {        
    
 db <- 
 db %>%
   mutate(UBox = `U-BOX DELIVERY INCOME` + `U-BOX OTHER INCOME` + `U-BOX STORAGE INCOME`,
          NOI = `STORAGE INCOME` + SALES + `MISCELLANEOUS INCOME` + UBox + `U-MOVE NET COMMISSION` - `COST OF SALES` - ADVERTISING - `LIABILITY INSURANCE` - PERSONNEL - `RENT-EQUIPMENT/LAND AND BLDGS` - `REPAIRS AND MAINTENANCE/GENERAL` - SUPPLIES - TELEPHONE - UTILITIES - `OTHER OPERATING EXPENSE`)
 
# }
 
 # Melt back to vertical format ----
 db <-
   melt(db, id = c("MONTH"))
    
    
# Import Fiscal Year Columns ----
  db$FY = " "
  db$FM = " "
  db$Quarter = " "
   
  
  for (i in 1:length(db$FY)){

    if(db$MONTH[i] >= '2015/1/1' & db$MONTH[i] <= '2015/3/1'){

      db$FY[i] = 2015
      db$Quarter[i] = 4

    } else if (db$MONTH[i] >= '2015/4/1' & db$MONTH[i] <= '2015/6/1') {

      db$FY[i] = 2016
      db$Quarter[i] = 1

    } else if (db$MONTH[i] >= '2015/7/1' & db$MONTH[i] <= '2015/9/1') {

      db$FY[i] = 2016
      db$Quarter[i] = 2

    } else if (db$MONTH[i] >= '2015/10/1' & db$MONTH[i] <= '2015/12/1'){

      db$FY[i] = 2016
      db$Quarter[i] = 3

    } else if (db$MONTH[i] >= '2016/1/1' & db$MONTH[i] <= '2016/3/1'){

      db$FY[i] = 2016
      db$Quarter[i] = 4

    } else if (db$MONTH[i] >= '2016/4/1' & db$MONTH[i] <= '2016/6/1'){

      db$FY[i] = 2017
      db$Quarter[i] = 1

    } else if (db$MONTH[i] >= '2016/7/1' & db$MONTH[i] <= '2016/9/1'){

      db$FY[i] = 2017
      db$Quarter[i] = 2

    } else if (db$MONTH[i] >= '2016/10/1' & db$MONTH[i] <= '2016/12/1'){

      db$FY[i] = 2017
      db$Quarter[i] = 3

    } else if (db$MONTH[i] >= '2017/1/1' & db$MONTH[i] <= '2017/3/1'){

      db$FY[i] = 2017
      db$Quarter[i] = 4

    } else if (db$MONTH[i] >= '2017/4/1' & db$MONTH[i] <= '2017/6/1'){

      db$FY[i] = 2018
      db$Quarter[i] = 1

    } else if (db$MONTH[i] >= '2017/7/1' & db$MONTH[i] <= '2017/9/1'){

      db$FY[i] = 2018
      db$Quarter[i] = 2

    } else if (db$MONTH[i] >= '2017/10/1' & db$MONTH[i] <= '2017/12/1'){

      db$FY[i] = 2018
      db$Quarter[i] = 3

    } else if (db$MONTH[i] >= '2018/1/1' & db$MONTH[i] <= '2018/3/1'){

      db$FY[i] = 2018
      db$Quarter[i] = 4

    } else if (db$MONTH[i] >= '2018/4/1' & db$MONTH[i] <= '2018/6/1'){

      db$FY[i] = 2019
      db$Quarter[i] = 1

    } else if (db$MONTH[i] >= '2018/7/1' & db$MONTH[i] <= '2018/9/1'){

      db$FY[i] = 2019
      db$Quarter[i] = 2

    }
  }
  
  
   # Addition of Month Column ----
   db$Month = " "

  for (i in 1:length(db$Month)){
    db$Month[i] = format(db$MONTH[i], "%b")
  }
  for (i in 1:length(db$FM)){
    if(month(db$MONTH[i]) >= 4 & month(db$MONTH[i]) <= 12){
      db$FM[i] = month(db$MONTH[i]) - 3
    } else if (month(db$MONTH[i]) == 1) {
      db$FM[i] = 10
    } else if (month(db$MONTH[i]) == 2) {
      db$FM[i] = 11
    } else if (month(db$MONTH[i]) == 3){
      db$FM[i] = 12
    }
  }
  
  # Rename Columns ----
  colnames(db) = c('Date', "Line Item", "Value", "FY", "FM", "Quarter", "Month") 

  return(db)
  
}





```




------------------------------------------------------------------
---
# ** Test Environment For Writing of Income Statement Function **
---
------------------------------------------------------------------

```{r}

# Final Acquisition list ----
acq_list_final

acq_test <-
  acq_list_final[328:330,   ]

profitcenter_list <- acq_test$Profit_Center



# Rename Column headers to Months (currently accounting periods) ----
colnames(test_db)[11] <- 4
colnames(test_db)[12] <- 5
colnames(test_db)[13] <- 6
colnames(test_db)[14] <- 7
colnames(test_db)[15] <- 8
colnames(test_db)[16] <- 9
colnames(test_db)[17] <- 10
colnames(test_db)[18] <- 11
colnames(test_db)[19] <- 12
colnames(test_db)[20] <- 1
colnames(test_db)[21] <- 2
colnames(test_db)[22] <- 3


# Two step filter process ----

  # SAP Accounts ----
  sap_accounts

  # 1 filter for profit centers & accounts (total) ----
  # Convert Profit Center column to Character ----
  test_db$`PROFIT CENTER` <- as.character(test_db$`PROFIT CENTER`)
  test_db$ACCOUNT <- as.character(test_db$ACCOUNT)


 db <-
  test_db %>% 
    filter(`PROFIT CENTER` %in% profitcenter_list &
            `ACCOUNT` %in% sap_accounts$SAP_number &
             `Fiscal Year` >= 2015)

  # Eliminate Unecessary columns ----
  db <-
    db[ , -c(1,3,4,5,9,10,23,24,26, 27)]

 
    test_melt <- 
      melt(db, id = c('PROFIT CENTER', "MEntity", "ACCOUNT", "DESCRIPTION", "Fiscal Year"))
    
    
# Rename columns ----
colnames(test_melt)[3] <- "SAP_number" 
colnames(test_melt)[7] <- "Amount"
colnames(test_melt)[6] <- "Cal_Month"


  test_melt$Cal_Month <- as.character(test_melt$Cal_Month)
  test_melt$Cal_Month <- as.numeric(test_melt$Cal_Month)
  test_melt$SAP_number <- as.character(test_melt$SAP_number)
  

# Creation of Calendar "MONTH" column ----
test_melt$Cal_Year = " "

for (i in 1:length(test_melt$`PROFIT CENTER`)){
  
  if(test_melt$Cal_Month[i] >= 4 & test_melt$Cal_Month[i] <= 12){
    
    test_melt$Cal_Year[i] = test_melt$`Fiscal Year`[i] - 1
    
  } else {
    
    test_melt$Cal_Year[i] = test_melt$`Fiscal Year`[i] 
    
  }
  
}

  
 test_melt$MONTH <- 
   paste(test_melt$Cal_Year, test_melt$Cal_Month, 1, sep = "-")
  
   test_melt$MONTH <- as.Date(test_melt$MONTH, format = "%Y-%m-%d")
   
   # Summarize Income Statement database ----
   test_melt <-
     test_melt %>%
     filter(SAP_number %in% sap_accounts$SAP_number)
   
   # Convert Chart of Accounts "SAP_Number" into character ----
   chart_of_accounts$SAP_number <- as.character(chart_of_accounts$SAP_number)
   
   
   test_melt <-
     left_join(test_melt, chart_of_accounts[ ,c(1,4)], by = "SAP_number")
   
   
   colnames(test_melt)[10] <- "Line Item"
   
   
   # At this point, the data is set up in a way that we have individual account numbers and their associated Line Items that we can aggregate. This next step is what we will need to compile in order to avoid an error when account numbers and their line items are not present in the database. The goal is to determine the minimum Month and create a default value of 0 should the accounts and line items not be available. 
   
   
   # ------------------
   # Creation of Shell 
   # ------------------
   
   line_item_function <- as.function(x, df){
     
     require(dplyr)
     require(purrr)
     
     min_is_month <- min(df$MONTH)
     max_is_month <- as.Date('2018-09-01')
     
     
     
     
     
     
     
     
   }
   
   
   
   # Determine Minimum Income Statement Data Month ----
   min_is_month <- min(test_melt$MONTH)
   max_is_month <- as.Date('2018-09-01')
   
   # --------
   # Storage 
   # --------
   
   # Individual Line item compilation ----
   storage_income_is <- 
     test_melt %>%
     filter(Line.Item == 'STORAGE INCOME') %>%
     group_by(MONTH, Line.Item) %>%
     summarize(Amount = sum(Amount))
   
   # Calculate the date difference between min income statement data and line item data ----
   monnb <- function(d) { lt <- as.POSIXlt(as.Date(d, origin = "1900-01-01")); lt$year*12 + lt$mon } 
   
   mondf <- function(d1, d2) { monnb(d2) - monnb(d1) }
   
   storage_date_diff <- mondf(min_is_month, min(storage_income_is$MONTH))
   
     # Date Difference Logical Flow. 
     # if Date > 0; min Month is lower than Line Item Minimum. We will need to fill in the remaining dates ----
   
   if(storage_date_diff > 0){
   
   date_seq <-
     seq.Date(from = min_is_month, to = min(storage_income_is$MONTH) - 1, by = "month")
   
   fill_df <-
     as.data.frame(date_seq)
   
     # Rename column ----
     colnames(fill_df) <- "MONTH"
     
     fill_df$Line.Item <- storage_income_is$Line.Item
     fill_df$Amount = 0
   
   
     # Bind Dataframes ----
     storage_income_is_test <-
       bind_rows(fill_df, storage_income_is)
   
   } else if (sum(test_melt$`Line Item` == "STORAGE INCOME") == 0) {
     
     full_date <- 
       seq.Date(from = min_is_month, to = max_is_month, by = "month")
     
     full_fill <- 
       as.data.frame(full_date)
     
     # Rename to Month ----
     colnames(full_fill) <- "MONTH"
     
     full_fill$Line.Item <- "STORAGE INCOME"
     full_fill$Amount = 0
     
   }
   

   
   
   
   # ------
   # Sales 
   # ------
   
   # Individual Line item compilation ----
   sales_is <- 
     test_melt %>%
     filter(Line.Item == 'SALES') %>%
     group_by(MONTH, Line.Item) %>%
     summarize(Amount = sum(Amount))
   
   # Calculate the date difference between min income statement data and line item data ----
   storage_date_diff <- mondf(min_is_month, min(storage_income_is$MONTH))
   
     # Date Difference Logical Flow. 
     # if Date > 0; min Month is lower than Line Item Minimum. We will need to fill in the remaining dates ----
   
   if(storage_date_diff > 0){
   
   date_seq <-
     seq.Date(from = min_is_month, to = min(storage_income_is$MONTH) - 1, by = "month")
   
   fill_df <-
     as.data.frame(date_seq)
   
     # Rename column ----
     colnames(fill_df) <- "MONTH"
     
     fill_df$Line.Item <- storage_income_is$Line.Item
     fill_df$Amount = 0
   
   
     # Bind Dataframes ----
     storage_income_is_test <-
       bind_rows(fill_df, storage_income_is)
   
   } 
   
   
   
   
  test_income_statement <-     
  test_melt %>%
  group_by(MONTH, `Line Item`) %>%
   summarise(Value = sum(Amount)) 
  
  
  # Logical check for ADVERTISING column ----
  test_filter <- !grepl("AD", colnames(test_cast))
  
  
  # Reshape to Calculate NOI and U-Box Aggregations ----
   test_cast <- 
     tidyr::spread(test_income_statement, `Line Item`, Value)
  
  
```



--- 
###* Test Function*
---

```{r}

test_function <- map(quarter_list, income_statment_compilation, accounts = sap_accounts$SAP_number)

```














