---
title: "Trend IS Data Verification"
author: "Noe Navarro"
date: "August 22, 2018"
output: html_document
---


```{r}

# Connection
  con.FinAccounting = DBI::dbConnect(odbc::odbc(), 
      Driver = "SQL Server",
      Server = "OPSREPORT02.UHAUL.AMERCO.ORG",
      Database = "FinAccounting",
      UID = rstudioapi::askForPassword("Database user"),
      PWD = rstudioapi::askForPassword("Database password"),
      Port = 1433)


 con.mentity
 dlr01 <- dplyr::tbl(con.mentity, "ENTITY_DLR01")

# Import Database 
  trend.is.detail <- dplyr::tbl(con.FinAccounting, "SAP_IS_UHAL_GROUP") 


```


```{r}

# Database 
  trend.is.detail <- collect(trend.is.detail)

  trend.is.detail$ACCOUNT <- as.character(trend.is.detail$ACCOUNT)
   
# 10-K Accounts
  k.accounts <- c(420000, 420010, 420030, 420040, 420050, 420060) #420100, 420110, 420120)
  
  #c(420000, 420010, 420030, 420040, 420050, 420060, 420100, 420110, 420120)
  
  k.accounts <- as.character(k.accounts)
  
  
  
# Import MEntity List Currently Used ----
mentity.list <- 
  read.csv("C:\\Users\\1217543\\Desktop\\Mentity_List.csv")

mentity.list <-
  as.character(mentity.list$MEntity)

  
  
```



```{r}


# Summarise by 10-K Accounts
  trend.is.detail <- 
  trend.is.detail %>%
    filter(ACCOUNT %in% k.accounts) #& MEntity %in% mentity.list)
  
  # Filter for F19 
  trend.is.detail.19 <- 
  trend.is.detail %>% 
  filter(`Fiscal Year` == 2019)
  
  # Filter for F18
  trend.is.detail.18 <- 
    trend.is.detail %>%
    filter(`Fiscal Year` == 2018)

# Summarise by Column
  Q1F19 <- 
  trend.is.detail.19 %>% 
    summarise(Q1 = sum(`PD 01`) + sum(`PD 02`) + sum(`PD 03`))
  
  Q4F18 <- 
    trend.is.detail.18 %>%
    summarise(Q2_to_4 = sum(`PD 04`) + sum(`PD 05`) + sum(`PD 06`) + sum(`PD 07`) + sum(`PD 08`) + sum(`PD 09`) + sum(`PD 10`) + sum(`PD 11`) + sum(`PD 12`))

  
  
  Q1F19
  
  Q4F18
  
  
  
# Distinct MEntity and Profit Centers
 # mentity_n_entity <- 
 # trend.is.detail.19 %>%
    #filter()
    #select(MEntity, `PROFIT CENTER`)
  
  
  # Distinct Values
  #d.mentity.is <- 
    #mentity_n_entity %>%
     # distinct(MEntity)
  
  
  SAP.Hierarchy
  
  
```




# Center Entity Name

```{r}

entity_df <-
  read.csv("\\\\adfs01.uhi.amerco\\users\\1217543\\Misc\\entity_names.csv", header = TRUE)

entity_df$Profit_Center <- as.character(entity_df$Profit_Center)

# Column type update
  colnames(entity_df)[8] <- "Entity"
  colnames(entity_df)[9] <- "Entity_Current"
  
  entity_df$Entity <- as.character(entity_df$Entity)
  entity_df$Entity_Current <- as.character(entity_df$Entity_Current)
  
  


dlr01 <- 
  collect(dlr01)

# Update Permanent Entity column to Entity
  colnames(dlr01)[4] <- "Entity"
  
  dlr01$Entity_Current <- dlr01$Entity

  dlr01 <- 
  dlr01 %>% filter(STATUS == 'O')
  
  dlr01$Entity <- as.character(dlr01$Entity)
  dlr01$Entity_Current <- as.character(dlr01$Entity_Current)
  
  
  # 380 rows
  names <- 
    left_join(entity_df, dlr01[ , c(4, 42)], by = "Entity")
  
  names2 <-
    left_join(names, dlr01[ , c(199, 42)], by = "Entity_Current")
  
  
  
  names2$ENTITY_NAME.x <- 
  gsub("\\*", "", names2$ENTITY_NAME.x)
  
  names2$ENTITY_NAME.y <- 
    gsub("\\*", "", names2$ENTITY_NAME.y)
  
  
  colnames(names2)[24] <- "Permanent_Entity_Name"
  colnames(names2)[25] <- "Current_Entity_Name"

  write.csv(names2, "U:\\Jason's Slide 2018\\entity_names.csv" )
```



# Using the SAP Hierarchy
```{r}


colnames(SAP.Hierarchy)[12] <- "Profit_Center"

sap_names <- 
left_join(entity_df, SAP.Hierarchy[ , c(12, 4)], by = "Profit_Center")

sap_names_unique <- 
unique(sap_names[, c('Profit_Center', 'Name')])

sap_names_unique %>% filter(is.na(sap_names_unique$Name))


# NA
sap_names %>% filter(is.na(Name))



```








```{r}


still_missing <- read.csv("\\\\adfs01.uhi.amerco\\users\\1217543\\Jason's Slide 2018\\final_names.csv")

still_missing$Profit_Center <- as.character(still_missing$Profit_Center)

db_names <- left_join(still_missing, SAP.Hierarchy[ ,c( 3, 4)], by = "Profit_Center")

db_names_unique <- 
unique(db_names[, c('Profit_Center', 'Name')])


# Export to csv
  write.csv(db_names_unique, "U:\\Jason's Slide 2018\\db_names.csv")




grep("Profit_Center", colnames(SAP.Hierarchy))


```






